import DOMPurify from 'dompurify';

/**
 * The one place any AI-generated or otherwise externally-sourced HTML is
 * cleaned before it's ever assigned to `innerHTML`/`dangerouslySetInnerHTML`.
 *
 * Why this exists: `marked.parse()` (see lib/chat-markdown.ts) passes raw
 * HTML embedded in the source text straight through unchanged — a chat
 * response is text generated by an AI model, not something this app wrote,
 * so a prompt-injected `<script>` or an `onerror=` handler in an `<img>`
 * would otherwise execute in the viewing user's own browser session
 * (their own conversation, not another user's data or this app's backend —
 * but still real, and cheap to close off). DOMPurify strips exactly that
 * class of thing while leaving normal markdown output (headings, lists,
 * tables, links, code blocks, safe inline styles) untouched.
 *
 * Only ever called client-side (from inside a `useEffect`, after mount —
 * see message-content.tsx) — DOMPurify needs a real `window`/DOM, which
 * doesn't exist during this app's static-export build step.
 */
export function sanitizeHtml(html: string): string {
  return DOMPurify.sanitize(html, {
    // Belt-and-braces on top of DOMPurify's own script/event-handler
    // stripping — even a sanitized <iframe>/<object>/<embed> with a safe
    // `src` still isn't something a chat message should ever render.
    FORBID_TAGS: ['iframe', 'object', 'embed', 'style'],
  });
}
